before_script :
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn install

language: node_js
node_js:
  - "10"

sudo: required

services:
  - docker

script:
- docker run --privileged -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --budget.configPath /sitespeed.io/homeBudget.json -n 1 https://c225b9fc.ngrok.io
# - yarn run size

after_success:
  - yarn run lh -- --perf=90 https://c225b9fc.ngrok.io