language: node_js
node_js:
  - "10"
sudo: required
services:
  - docker
script:
  - docker run --privileged --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io http://48bbcf6e.ngrok.io -n 1 --budget.configPath homeBudget.json
