language: node_js
node_js:
  - "10"

sudo: required

services:
  - docker

script:
- docker run --privileged -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --budget.configPath myBudget.json -n 1 https://803b6cc40ee5.ngrok.io
# - yarn run size

after_success:
  - yarn run lh -- --perf=90 https://803b6cc40ee5.ngrok.io
