language: node_js
node_js:
  - "10"

sudo: required

services:
  - docker

script:
- docker run --privileged -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --budget.configPath /sitespeed.io/budget.json -n 1 https://1ce0-79-101-188-107.ngrok-free.app
# - yarn run size

after_success:
  - yarn run lh -- --perf=90 https://dev.to