name: JS Budjet Check

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v1
      - name: run sitespeedio test
        uses: docker://sitespeedio/sitespeed.io:12.11.0-action
        with:
          args: http://97e7d096f805.ngrok.io/ -n 1 --budget.configPath /github/workspace/config/budgets/home.json
