name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: run sitespeedio test
      uses: docker://sitespeedio/sitespeed.io:12.0.1-action
      with:
        args: http://4cdecf54.ngrok.io -n 1 --budget.configPath /github/workspace/budget.json
