name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v1
      - name: run sitespeedio test
        uses: docker://sitespeedio/sitespeed.io:latest
        with:
          args: http://8eab-37-214-82-10.ngrok.io/ -n 1 --budget.configPath /github/workspace/config/budget.json
