name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v1
      - name: run sitespeed.io test
        uses: docker://sitespeedio/sitespeed.io:latest
        with:
          args: https://d29c-91-232-196-17.ngrok.io -n 1 --budget.configPath /github/workspace/homeBudget.json
