name: javascript-budget-check

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: run sitespeedio test
        uses: docker://sitespeedio/sitespeed.io:latest
        with:
          args: http://f838630b4160.ngrok.io/ -n 1 --budget.configPath /github/workspace/homeBudget.json